/**
 * InventoryAPI
 * Orkiv Inventory API client 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package InventoryClient.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;


/**
 * ItemRequest
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-08-05T15:11:04.542-04:00")
public class ItemRequest   {
  @SerializedName("id")
  private String id = null;

  @SerializedName("category")
  private String category = null;

  @SerializedName("desc")
  private String desc = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("ordprice")
  private BigDecimal ordprice = null;

  @SerializedName("price")
  private String price = null;

  @SerializedName("quantity")
  private String quantity = null;

  public ItemRequest id(String id) {
    this.id = id;
    return this;
  }

   /**
   * ID of item
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "ID of item")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ItemRequest category(String category) {
    this.category = category;
    return this;
  }

   /**
   * Category ID of item
   * @return category
  **/
  @ApiModelProperty(example = "null", value = "Category ID of item")
  public String getCategory() {
    return category;
  }

  public void setCategory(String category) {
    this.category = category;
  }

  public ItemRequest desc(String desc) {
    this.desc = desc;
    return this;
  }

   /**
   * Rich text description of item
   * @return desc
  **/
  @ApiModelProperty(example = "null", value = "Rich text description of item")
  public String getDesc() {
    return desc;
  }

  public void setDesc(String desc) {
    this.desc = desc;
  }

  public ItemRequest name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of item
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "Name of item")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ItemRequest ordprice(BigDecimal ordprice) {
    this.ordprice = ordprice;
    return this;
  }

   /**
   * Integer value of price
   * @return ordprice
  **/
  @ApiModelProperty(example = "null", value = "Integer value of price")
  public BigDecimal getOrdprice() {
    return ordprice;
  }

  public void setOrdprice(BigDecimal ordprice) {
    this.ordprice = ordprice;
  }

  public ItemRequest price(String price) {
    this.price = price;
    return this;
  }

   /**
   * String value of price
   * @return price
  **/
  @ApiModelProperty(example = "null", value = "String value of price")
  public String getPrice() {
    return price;
  }

  public void setPrice(String price) {
    this.price = price;
  }

  public ItemRequest quantity(String quantity) {
    this.quantity = quantity;
    return this;
  }

   /**
   * Inventory quantity
   * @return quantity
  **/
  @ApiModelProperty(example = "null", value = "Inventory quantity")
  public String getQuantity() {
    return quantity;
  }

  public void setQuantity(String quantity) {
    this.quantity = quantity;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ItemRequest itemRequest = (ItemRequest) o;
    return Objects.equals(this.id, itemRequest.id) &&
        Objects.equals(this.category, itemRequest.category) &&
        Objects.equals(this.desc, itemRequest.desc) &&
        Objects.equals(this.name, itemRequest.name) &&
        Objects.equals(this.ordprice, itemRequest.ordprice) &&
        Objects.equals(this.price, itemRequest.price) &&
        Objects.equals(this.quantity, itemRequest.quantity);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, category, desc, name, ordprice, price, quantity);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ItemRequest {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("    desc: ").append(toIndentedString(desc)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    ordprice: ").append(toIndentedString(ordprice)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

