/**
 * InventoryAPI
 * Orkiv Inventory API client 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package InventoryClient.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;


/**
 * Variation
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-08-05T15:11:04.542-04:00")
public class Variation   {
  @SerializedName("name")
  private String name = null;

  @SerializedName("priceChange")
  private BigDecimal priceChange = null;

  @SerializedName("id")
  private String id = null;

  public Variation name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Variation name
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "Variation name")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Variation priceChange(BigDecimal priceChange) {
    this.priceChange = priceChange;
    return this;
  }

   /**
   * New price to set if variation is set (in hundreds)
   * @return priceChange
  **/
  @ApiModelProperty(example = "null", value = "New price to set if variation is set (in hundreds)")
  public BigDecimal getPriceChange() {
    return priceChange;
  }

  public void setPriceChange(BigDecimal priceChange) {
    this.priceChange = priceChange;
  }

  public Variation id(String id) {
    this.id = id;
    return this;
  }

   /**
   * System ID of variation
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "System ID of variation")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Variation variation = (Variation) o;
    return Objects.equals(this.name, variation.name) &&
        Objects.equals(this.priceChange, variation.priceChange) &&
        Objects.equals(this.id, variation.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, priceChange, id);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Variation {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    priceChange: ").append(toIndentedString(priceChange)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

