/**
 * InventoryAPI
 * Orkiv Inventory API client 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package Inventory_client;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * Category
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-08-04T12:29:14.613-04:00")
public class Category   {
  @SerializedName("name")
  private String name = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("parent")
  private String parent = null;

  public Category name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of category
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "Name of category")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Category id(String id) {
    this.id = id;
    return this;
  }

   /**
   * ID of category
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "ID of category")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Category parent(String parent) {
    this.parent = parent;
    return this;
  }

   /**
   * ID of parent element. Top level categories are set to root.
   * @return parent
  **/
  @ApiModelProperty(example = "null", value = "ID of parent element. Top level categories are set to root.")
  public String getParent() {
    return parent;
  }

  public void setParent(String parent) {
    this.parent = parent;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Category category = (Category) o;
    return Objects.equals(this.name, category.name) &&
        Objects.equals(this.id, category.id) &&
        Objects.equals(this.parent, category.parent);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, id, parent);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Category {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    parent: ").append(toIndentedString(parent)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

