/**
 * InventoryAPI
 * Orkiv Inventory API client 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package Inventory_client;

import java.util.Objects;
import Inventory_client.Dictionary;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * EventRequest
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-08-04T12:29:14.613-04:00")
public class EventRequest   {
  @SerializedName("url")
  private String url = null;

  @SerializedName("serviceid")
  private String serviceid = null;

  @SerializedName("postbody")
  private Dictionary postbody = null;

  public EventRequest url(String url) {
    this.url = url;
    return this;
  }

   /**
   * URL for the server to request on successful subscription to specified service
   * @return url
  **/
  @ApiModelProperty(example = "null", value = "URL for the server to request on successful subscription to specified service")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public EventRequest serviceid(String serviceid) {
    this.serviceid = serviceid;
    return this;
  }

   /**
   * ServiceID to bind event to.
   * @return serviceid
  **/
  @ApiModelProperty(example = "null", value = "ServiceID to bind event to.")
  public String getServiceid() {
    return serviceid;
  }

  public void setServiceid(String serviceid) {
    this.serviceid = serviceid;
  }

  public EventRequest postbody(Dictionary postbody) {
    this.postbody = postbody;
    return this;
  }

   /**
   * Get postbody
   * @return postbody
  **/
  @ApiModelProperty(example = "null", value = "")
  public Dictionary getPostbody() {
    return postbody;
  }

  public void setPostbody(Dictionary postbody) {
    this.postbody = postbody;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EventRequest eventRequest = (EventRequest) o;
    return Objects.equals(this.url, eventRequest.url) &&
        Objects.equals(this.serviceid, eventRequest.serviceid) &&
        Objects.equals(this.postbody, eventRequest.postbody);
  }

  @Override
  public int hashCode() {
    return Objects.hash(url, serviceid, postbody);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EventRequest {\n");
    
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    serviceid: ").append(toIndentedString(serviceid)).append("\n");
    sb.append("    postbody: ").append(toIndentedString(postbody)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

