/**
 * InventoryAPI
 * Orkiv Inventory API client 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package Inventory_client;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;


/**
 * Order
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-08-04T12:29:14.613-04:00")
public class Order   {
  @SerializedName("order_id")
  private String orderId = null;

  @SerializedName("info_email")
  private String infoEmail = null;

  @SerializedName("info_first")
  private String infoFirst = null;

  @SerializedName("info_last")
  private String infoLast = null;

  @SerializedName("phone")
  private String phone = null;

  @SerializedName("shipset")
  private Boolean shipset = null;

  @SerializedName("info_adr1")
  private String infoAdr1 = null;

  @SerializedName("info_adr2")
  private String infoAdr2 = null;

  @SerializedName("info_cty")
  private String infoCty = null;

  @SerializedName("info_zip")
  private String infoZip = null;

  @SerializedName("state")
  private String state = null;

  @SerializedName("info_sadr1")
  private String infoSadr1 = null;

  @SerializedName("info_sadr2")
  private String infoSadr2 = null;

  @SerializedName("info_scty")
  private String infoScty = null;

  @SerializedName("info_szip")
  private String infoSzip = null;

  @SerializedName("sstate")
  private String sstate = null;

  @SerializedName("tax_amount")
  private Float taxAmount = null;

  @SerializedName("shipping_amount")
  private Float shippingAmount = null;

  @SerializedName("amount_total")
  private Float amountTotal = null;

  @SerializedName("itemIDs")
  private List<String> itemIDs = new ArrayList<String>();

  public Order orderId(String orderId) {
    this.orderId = orderId;
    return this;
  }

   /**
   * Order ID
   * @return orderId
  **/
  @ApiModelProperty(example = "null", value = "Order ID")
  public String getOrderId() {
    return orderId;
  }

  public void setOrderId(String orderId) {
    this.orderId = orderId;
  }

  public Order infoEmail(String infoEmail) {
    this.infoEmail = infoEmail;
    return this;
  }

   /**
   * Customer email
   * @return infoEmail
  **/
  @ApiModelProperty(example = "null", value = "Customer email")
  public String getInfoEmail() {
    return infoEmail;
  }

  public void setInfoEmail(String infoEmail) {
    this.infoEmail = infoEmail;
  }

  public Order infoFirst(String infoFirst) {
    this.infoFirst = infoFirst;
    return this;
  }

   /**
   * Customer first name
   * @return infoFirst
  **/
  @ApiModelProperty(example = "null", value = "Customer first name")
  public String getInfoFirst() {
    return infoFirst;
  }

  public void setInfoFirst(String infoFirst) {
    this.infoFirst = infoFirst;
  }

  public Order infoLast(String infoLast) {
    this.infoLast = infoLast;
    return this;
  }

   /**
   * Customer last name
   * @return infoLast
  **/
  @ApiModelProperty(example = "null", value = "Customer last name")
  public String getInfoLast() {
    return infoLast;
  }

  public void setInfoLast(String infoLast) {
    this.infoLast = infoLast;
  }

  public Order phone(String phone) {
    this.phone = phone;
    return this;
  }

   /**
   * Customer phone number
   * @return phone
  **/
  @ApiModelProperty(example = "null", value = "Customer phone number")
  public String getPhone() {
    return phone;
  }

  public void setPhone(String phone) {
    this.phone = phone;
  }

  public Order shipset(Boolean shipset) {
    this.shipset = shipset;
    return this;
  }

   /**
   * Customer billing address matches shipping address
   * @return shipset
  **/
  @ApiModelProperty(example = "null", value = "Customer billing address matches shipping address")
  public Boolean getShipset() {
    return shipset;
  }

  public void setShipset(Boolean shipset) {
    this.shipset = shipset;
  }

  public Order infoAdr1(String infoAdr1) {
    this.infoAdr1 = infoAdr1;
    return this;
  }

   /**
   * Customer billing address line '1'
   * @return infoAdr1
  **/
  @ApiModelProperty(example = "null", value = "Customer billing address line '1'")
  public String getInfoAdr1() {
    return infoAdr1;
  }

  public void setInfoAdr1(String infoAdr1) {
    this.infoAdr1 = infoAdr1;
  }

  public Order infoAdr2(String infoAdr2) {
    this.infoAdr2 = infoAdr2;
    return this;
  }

   /**
   * Customer billing address line '2'
   * @return infoAdr2
  **/
  @ApiModelProperty(example = "null", value = "Customer billing address line '2'")
  public String getInfoAdr2() {
    return infoAdr2;
  }

  public void setInfoAdr2(String infoAdr2) {
    this.infoAdr2 = infoAdr2;
  }

  public Order infoCty(String infoCty) {
    this.infoCty = infoCty;
    return this;
  }

   /**
   * Customer billing city
   * @return infoCty
  **/
  @ApiModelProperty(example = "null", value = "Customer billing city")
  public String getInfoCty() {
    return infoCty;
  }

  public void setInfoCty(String infoCty) {
    this.infoCty = infoCty;
  }

  public Order infoZip(String infoZip) {
    this.infoZip = infoZip;
    return this;
  }

   /**
   * Customer billing zip code
   * @return infoZip
  **/
  @ApiModelProperty(example = "null", value = "Customer billing zip code")
  public String getInfoZip() {
    return infoZip;
  }

  public void setInfoZip(String infoZip) {
    this.infoZip = infoZip;
  }

  public Order state(String state) {
    this.state = state;
    return this;
  }

   /**
   * Customer billing state
   * @return state
  **/
  @ApiModelProperty(example = "null", value = "Customer billing state")
  public String getState() {
    return state;
  }

  public void setState(String state) {
    this.state = state;
  }

  public Order infoSadr1(String infoSadr1) {
    this.infoSadr1 = infoSadr1;
    return this;
  }

   /**
   * Customer shipping address line '1'
   * @return infoSadr1
  **/
  @ApiModelProperty(example = "null", value = "Customer shipping address line '1'")
  public String getInfoSadr1() {
    return infoSadr1;
  }

  public void setInfoSadr1(String infoSadr1) {
    this.infoSadr1 = infoSadr1;
  }

  public Order infoSadr2(String infoSadr2) {
    this.infoSadr2 = infoSadr2;
    return this;
  }

   /**
   * Customer shipping address line '2'
   * @return infoSadr2
  **/
  @ApiModelProperty(example = "null", value = "Customer shipping address line '2'")
  public String getInfoSadr2() {
    return infoSadr2;
  }

  public void setInfoSadr2(String infoSadr2) {
    this.infoSadr2 = infoSadr2;
  }

  public Order infoScty(String infoScty) {
    this.infoScty = infoScty;
    return this;
  }

   /**
   * Customer shipping city
   * @return infoScty
  **/
  @ApiModelProperty(example = "null", value = "Customer shipping city")
  public String getInfoScty() {
    return infoScty;
  }

  public void setInfoScty(String infoScty) {
    this.infoScty = infoScty;
  }

  public Order infoSzip(String infoSzip) {
    this.infoSzip = infoSzip;
    return this;
  }

   /**
   * Customer shipping zip code
   * @return infoSzip
  **/
  @ApiModelProperty(example = "null", value = "Customer shipping zip code")
  public String getInfoSzip() {
    return infoSzip;
  }

  public void setInfoSzip(String infoSzip) {
    this.infoSzip = infoSzip;
  }

  public Order sstate(String sstate) {
    this.sstate = sstate;
    return this;
  }

   /**
   * Customer shipping state
   * @return sstate
  **/
  @ApiModelProperty(example = "null", value = "Customer shipping state")
  public String getSstate() {
    return sstate;
  }

  public void setSstate(String sstate) {
    this.sstate = sstate;
  }

  public Order taxAmount(Float taxAmount) {
    this.taxAmount = taxAmount;
    return this;
  }

   /**
   * Tax amount in hundreds. Must divide by '100' for USD value
   * @return taxAmount
  **/
  @ApiModelProperty(example = "null", value = "Tax amount in hundreds. Must divide by '100' for USD value")
  public Float getTaxAmount() {
    return taxAmount;
  }

  public void setTaxAmount(Float taxAmount) {
    this.taxAmount = taxAmount;
  }

  public Order shippingAmount(Float shippingAmount) {
    this.shippingAmount = shippingAmount;
    return this;
  }

   /**
   * Shipping total in USD
   * @return shippingAmount
  **/
  @ApiModelProperty(example = "null", value = "Shipping total in USD")
  public Float getShippingAmount() {
    return shippingAmount;
  }

  public void setShippingAmount(Float shippingAmount) {
    this.shippingAmount = shippingAmount;
  }

  public Order amountTotal(Float amountTotal) {
    this.amountTotal = amountTotal;
    return this;
  }

   /**
   * Checkout total in USD
   * @return amountTotal
  **/
  @ApiModelProperty(example = "null", value = "Checkout total in USD")
  public Float getAmountTotal() {
    return amountTotal;
  }

  public void setAmountTotal(Float amountTotal) {
    this.amountTotal = amountTotal;
  }

  public Order itemIDs(List<String> itemIDs) {
    this.itemIDs = itemIDs;
    return this;
  }

   /**
   * Array of items purchased at checkout
   * @return itemIDs
  **/
  @ApiModelProperty(example = "null", value = "Array of items purchased at checkout")
  public List<String> getItemIDs() {
    return itemIDs;
  }

  public void setItemIDs(List<String> itemIDs) {
    this.itemIDs = itemIDs;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Order order = (Order) o;
    return Objects.equals(this.orderId, order.orderId) &&
        Objects.equals(this.infoEmail, order.infoEmail) &&
        Objects.equals(this.infoFirst, order.infoFirst) &&
        Objects.equals(this.infoLast, order.infoLast) &&
        Objects.equals(this.phone, order.phone) &&
        Objects.equals(this.shipset, order.shipset) &&
        Objects.equals(this.infoAdr1, order.infoAdr1) &&
        Objects.equals(this.infoAdr2, order.infoAdr2) &&
        Objects.equals(this.infoCty, order.infoCty) &&
        Objects.equals(this.infoZip, order.infoZip) &&
        Objects.equals(this.state, order.state) &&
        Objects.equals(this.infoSadr1, order.infoSadr1) &&
        Objects.equals(this.infoSadr2, order.infoSadr2) &&
        Objects.equals(this.infoScty, order.infoScty) &&
        Objects.equals(this.infoSzip, order.infoSzip) &&
        Objects.equals(this.sstate, order.sstate) &&
        Objects.equals(this.taxAmount, order.taxAmount) &&
        Objects.equals(this.shippingAmount, order.shippingAmount) &&
        Objects.equals(this.amountTotal, order.amountTotal) &&
        Objects.equals(this.itemIDs, order.itemIDs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(orderId, infoEmail, infoFirst, infoLast, phone, shipset, infoAdr1, infoAdr2, infoCty, infoZip, state, infoSadr1, infoSadr2, infoScty, infoSzip, sstate, taxAmount, shippingAmount, amountTotal, itemIDs);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Order {\n");
    
    sb.append("    orderId: ").append(toIndentedString(orderId)).append("\n");
    sb.append("    infoEmail: ").append(toIndentedString(infoEmail)).append("\n");
    sb.append("    infoFirst: ").append(toIndentedString(infoFirst)).append("\n");
    sb.append("    infoLast: ").append(toIndentedString(infoLast)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    shipset: ").append(toIndentedString(shipset)).append("\n");
    sb.append("    infoAdr1: ").append(toIndentedString(infoAdr1)).append("\n");
    sb.append("    infoAdr2: ").append(toIndentedString(infoAdr2)).append("\n");
    sb.append("    infoCty: ").append(toIndentedString(infoCty)).append("\n");
    sb.append("    infoZip: ").append(toIndentedString(infoZip)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    infoSadr1: ").append(toIndentedString(infoSadr1)).append("\n");
    sb.append("    infoSadr2: ").append(toIndentedString(infoSadr2)).append("\n");
    sb.append("    infoScty: ").append(toIndentedString(infoScty)).append("\n");
    sb.append("    infoSzip: ").append(toIndentedString(infoSzip)).append("\n");
    sb.append("    sstate: ").append(toIndentedString(sstate)).append("\n");
    sb.append("    taxAmount: ").append(toIndentedString(taxAmount)).append("\n");
    sb.append("    shippingAmount: ").append(toIndentedString(shippingAmount)).append("\n");
    sb.append("    amountTotal: ").append(toIndentedString(amountTotal)).append("\n");
    sb.append("    itemIDs: ").append(toIndentedString(itemIDs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

